add_newline = true
format = "$character$all$cmd_duration"
right_format = "$git_branch$git_status"

[character]
error_symbol = "[âœ](bold red)"
success_symbol = "[âœ](bold green)"

[cmd_duration]
format = "took [$duration](bold yellow) "
min_time = 30000

[directory]
home_symbol = "ğŸ "
read_only = " ï ½"
style = "#47fea4"
truncation_length = 1
truncation_symbol = "ï»  "

[git_branch]
format = "(bold blue)[](bold blue)[ï˜ $branch(:$remote_branch)]($style)[](bold blue) "
style = "bold italic blue"
symbol = "ï˜ "

[git_status]
ahead = "ğŸğŸ’¨"
behind = "ğŸ˜°"
conflicted = "ğŸ³"
deleted = "([$count deleted ](italic red))"
disabled = false
diverged = "ğŸ˜µ"
format = "(ï  $up_to_date$staged$modified$renamed$deleted$untracked)($style)"
modified = "([$count modified ](italic fg:#47fea4))"
renamed = "([$count renamed ](italic green))"
staged = "([$count modified ](italic green))"
stashed = "ğŸ“¦"
style = "red"
untracked = "([$count untracked ](italic fg:#47fea4))"
up_to_date = "ï˜ "

[line_break]
disabled = false

[nix_shell]
symbol = "ï‹œ "

[package]
disabled = true

[sudo]
style = "bold green"
symbol = "ğŸ‘©â€ğŸ’» "
